"""empty message

Revision ID: 5326d64abdb9
Revises: 56922de1df47
Create Date: 2020-02-04 18:04:38.015969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5326d64abdb9'
down_revision = '56922de1df47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_network', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('charge_network', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_charge_network_created_at', table_name='charge_network')
    op.drop_index('ix_charge_network_updated_at', table_name='charge_network')
    op.drop_column('charge_network', 'created_at')
    op.drop_column('charge_network', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_network', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('charge_network', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_charge_network_updated_at', 'charge_network', ['updated_at'], unique=False)
    op.create_index('ix_charge_network_created_at', 'charge_network', ['created_at'], unique=False)
    op.drop_column('charge_network', 'time_updated')
    op.drop_column('charge_network', 'time_created')
    # ### end Alembic commands ###
