"""empty message

Revision ID: 62042ae2381d
Revises: fb2d7f74d102
Create Date: 2020-02-04 18:08:35.286243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62042ae2381d'
down_revision = 'fb2d7f74d102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_network', sa.Column('time_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charge_network', 'time_updated')
    # ### end Alembic commands ###
