
"""empty message

Revision ID: b2bc51552ed3
Revises: e93f1aadc526
Create Date: 2020-02-04 17:43:20.415027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2bc51552ed3'
down_revision = 'e93f1aadc526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_network', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('charge_network', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('charge_network', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('charge_network', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_charge_network_created_at'), 'charge_network', ['created_at'], unique=False)
    op.create_index(op.f('ix_charge_network_updated_at'), 'charge_network', ['updated_at'], unique=False)
    op.drop_index('ix_charge_network_timestamp', table_name='charge_network')
    op.drop_column('charge_network', 'timestamp')
    op.drop_column('charge_network', 'longitude')
    op.drop_column('charge_network', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_network', sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('charge_network', sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('charge_network', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_charge_network_timestamp', 'charge_network', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_charge_network_updated_at'), table_name='charge_network')
    op.drop_index(op.f('ix_charge_network_created_at'), table_name='charge_network')
    op.drop_column('charge_network', 'updated_at')
    op.drop_column('charge_network', 'lng')
    op.drop_column('charge_network', 'lat')
    op.drop_column('charge_network', 'created_at')
    # ### end Alembic commands ###
