"""empty message

Revision ID: d7939e1df0ae
Revises: f0336f04dac6
Create Date: 2020-02-04 18:11:06.643935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7939e1df0ae'
down_revision = 'f0336f04dac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge_network', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charge_network', 'time_updated')
    # ### end Alembic commands ###
